all: 
	make --file=rdopts-lib.mak
	make --file=rdopts-lib.mak clean
	make --file=cpc152svc.mak

clean:
	make --file=rdopts-lib.mak clean
	make --file=cpc152svc.mak clean
	
cleanall:
	make --file=rdopts-lib.mak cleanall
	make --file=cpc152svc.mak cleanall
